version: '3.5'

services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    restart: always
    volumes:
      - ./integration-tests:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: usertest
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - dev

  streaming-user:
    build: .
    env_file: local.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - dev

networks: 
  dev:
    name: strm_network